config/routes.rb
Agenda::Application.routes.draw do
  
  resources :copypastes

  resources :brainstorms

  root 'tasks#index'
  resources :tasks

  

end

app/models/brainstorm.rb
class Brainstorm < ActiveRecord::Base
end

app/models/copypaste.rb
class Copypaste < ActiveRecord::Base
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/brainstorms_controller.rb
class BrainstormsController < ApplicationController
  before_action :set_brainstorm, only: [:show, :edit, :update, :destroy]

  # GET /brainstorms
  # GET /brainstorms.json
  def index
    @brainstorms = Brainstorm.all
  end

  # GET /brainstorms/1
  # GET /brainstorms/1.json
  def show
  end

  # GET /brainstorms/new
  def new
    @brainstorm = Brainstorm.new
  end

  # GET /brainstorms/1/edit
  def edit
  end

  # POST /brainstorms
  # POST /brainstorms.json
  def create
    @brainstorm = Brainstorm.new(brainstorm_params)

    respond_to do |format|
      if @brainstorm.save
        format.html { redirect_to @brainstorm, notice: 'Brainstorm was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brainstorm }
      else
        format.html { render action: 'new' }
        format.json { render json: @brainstorm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brainstorms/1
  # PATCH/PUT /brainstorms/1.json
  def update
    respond_to do |format|
      if @brainstorm.update(brainstorm_params)
        format.html { redirect_to @brainstorm, notice: 'Brainstorm was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brainstorm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brainstorms/1
  # DELETE /brainstorms/1.json
  def destroy
    @brainstorm.destroy
    respond_to do |format|
      format.html { redirect_to brainstorms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brainstorm
      @brainstorm = Brainstorm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brainstorm_params
      params.require(:brainstorm).permit(:idea, :annotations)
    end
end

app/controllers/copypastes_controller.rb
class CopypastesController < ApplicationController
  before_action :set_copypaste, only: [:show, :edit, :update, :destroy]

  # GET /copypastes
  # GET /copypastes.json
  def index
    @copypastes = Copypaste.all
  end

  # GET /copypastes/1
  # GET /copypastes/1.json
  def show
  end

  # GET /copypastes/new
  def new
    @copypaste = Copypaste.new
  end

  # GET /copypastes/1/edit
  def edit
  end

  # POST /copypastes
  # POST /copypastes.json
  def create
    @copypaste = Copypaste.new(copypaste_params)

    respond_to do |format|
      if @copypaste.save
        format.html { redirect_to @copypaste, notice: 'Copypaste was successfully created.' }
        format.json { render action: 'show', status: :created, location: @copypaste }
      else
        format.html { render action: 'new' }
        format.json { render json: @copypaste.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /copypastes/1
  # PATCH/PUT /copypastes/1.json
  def update
    respond_to do |format|
      if @copypaste.update(copypaste_params)
        format.html { redirect_to @copypaste, notice: 'Copypaste was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @copypaste.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /copypastes/1
  # DELETE /copypastes/1.json
  def destroy
    @copypaste.destroy
    respond_to do |format|
      format.html { redirect_to copypastes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_copypaste
      @copypaste = Copypaste.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def copypaste_params
      params.require(:copypaste).permit(:content)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  caches_page :index

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @task_list = Task.all.group_by(&:context)
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    task_params[:status] = 'undone'
    @task = Task.new(task_params)
    @task.save
    expire_page action: 'index'
    redirect_to root_path
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:description, :context, :priority)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brainstorms_helper.rb
module BrainstormsHelper
end

app/helpers/copypastes_helper.rb
module CopypastesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/brainstorms/_form.html.erb
<%= form_for(@brainstorm) do |f| %>
  <% if @brainstorm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brainstorm.errors.count, "error") %> prohibited this brainstorm from being saved:</h2>

      <ul>
      <% @brainstorm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :idea %><br>
    <%= f.text_field :idea %>
  </div>
  <div class="field">
    <%= f.label :annotations %><br>
    <%= f.text_area :annotations %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/brainstorms/edit.html.erb
<h1>Editing brainstorm</h1>

<%= render 'form' %>

<%= link_to 'Show', @brainstorm %> |
<%= link_to 'Back', brainstorms_path %>

app/views/brainstorms/index.html.erb
<h1>Listing brainstorms</h1>

<table>
  <tbody>
    <% @brainstorms.each do |brainstorm| %>
      <tr>
        <td><%= link_to brainstorm.idea, brainstorm %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brainstorm', new_brainstorm_path %>

app/views/brainstorms/new.html.erb
<h1>New brainstorm</h1>

<%= render 'form' %>

<%= link_to 'Back', brainstorms_path %>

app/views/brainstorms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Idea:</strong>
  <%= @brainstorm.idea %>
</p>

<p>
  <strong>Annotations:</strong>
  <%= @brainstorm.annotations %>
</p>

<%= link_to 'Edit', edit_brainstorm_path(@brainstorm) %> |
<%= link_to 'Back', brainstorms_path %>

app/views/copypastes/_form.html.erb
<%= form_for(@copypaste) do |f| %>
  <% if @copypaste.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@copypaste.errors.count, "error") %> prohibited this copypaste from being saved:</h2>

      <ul>
      <% @copypaste.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/copypastes/edit.html.erb
<h1>Editing copypaste</h1>

<%= render 'form' %>

<%= link_to 'Show', @copypaste %> |
<%= link_to 'Back', copypastes_path %>

app/views/copypastes/index.html.erb
<h1>Listing copypastes</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @copypastes.each do |copypaste| %>
      <tr>
        <td><%= copypaste.content %></td>
        <td><%= link_to 'Show', copypaste %></td>
        <td><%= link_to 'Edit', edit_copypaste_path(copypaste) %></td>
        <td><%= link_to 'Destroy', copypaste, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Copypaste', new_copypaste_path %>

app/views/copypastes/new.html.erb
<h1>New copypaste</h1>

<%= render 'form' %>

<%= link_to 'Back', copypastes_path %>

app/views/copypastes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @copypaste.content %>
</p>

<%= link_to 'Edit', edit_copypaste_path(@copypaste) %> |
<%= link_to 'Back', copypastes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Agenda</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css" rel="stylesheet">
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Hurgonizator</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to 'New Task', new_task_path %></li>
            <li><a  data-toggle="modal" href="#horario">Horário</a></li>
            <li><%= link_to 'Brainstorm', brainstorms_path %></li>
            <li><%= link_to 'Copy & Paste', copypastes_path %></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>
  
  <div class="container">
    <%= yield %>
  </div>
  
  
  <!-- Modal -->
  <div class="modal fade" id="horario" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Horário</h4>
        </div>
        <div class="modal-body">
          <table class="table">
            <tr>
              <td>Redes</td>
              <td>Engenharia</td>
              <td>Engenharia</td>
              <td>Teoria Comp</td>
              <td></td>
            </tr>
            <tr>
              <td>B.D.</td>
              <td>Redes</td>
              <td>Empreend.</td>
              <td>Compiladores</td>
              <td>Compiladores</td>
            </tr>
            <tr>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
            <tr>
              <td>S.O.</td>
              <td>Teoria Comp</td>
              <td>Empreend.</td>
              <td>S.O.</td>
              <td></td>
            </tr>
            <tr>
              <td></td>
              <td></td>
              <td></td>
              <td>B.D.</td>
              <td></td>
            </tr>
          </table>
        </div>
      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->

  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js"></script>
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :context %><br>
    <!--<select name="task[context]" id="context_selector">
      <option value="formais">Formais</option>
      <option value="bd">B.D.</option>
      <option value="redes">Redes</option>
      <option value="so">S.O.</option>
      <option value="compiladores">Compiladores</option>
      <option value="teoria">Teoria</option>
      <option value="engenharia">Engenharia</option>
      <option value="">Outro</option>
    </select>-->
    <%= f.text_field :context, id: 'context' %>
  </div>
  <div class="field">
    <%= f.label :pririty %><br>
    <input type="range" name="task[pririty]" min="1" max="100">
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<table class="table">
  <tbody>
    <% @task_list.each do |ctx| %>
      <tr>
        <th><h3 class="uppercase"><%= ctx[0] %></h3></th>
        <th></th>
      </tr>
      <% ctx[1].each do |task| %>
        <tr>
          <td><%= best_in_place task, :description %></td>
          <td>
            <a data-confirm="Are you sure?" data-method="delete" href="/tasks/<%= task.id %>" rel="nofollow">
              <div class="btn btn-xs btn-danger"><span class="glyphicon glyphicon-remove"></span></div>
            </a>
          </td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<div class="alert alert-success"><%= notice %></div>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Context:</strong>
  <%= @task.context %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>